[build]
  command = "pnpm build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22"

[dev]
  command = "pnpm dev"
  targetPort = 3000
  framework = "#custom"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
